repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # Supprime les espaces inutiles
      - id: end-of-file-fixer    # Ajoute une ligne vide à la fin des fichiers
      - id: check-yaml           # Vérifie la syntaxe des fichiers YAML
      - id: check-added-large-files  # Empêche l'ajout de gros fichiers

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black  # Formatte le code Python selon PEP 8

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8  # Vérifie la qualité du code Python
